### ISSUE TITLE
Adding an additional Auth provider (Keycloak)

### ISSUE THREAD

**Issue by wint3ria** [mamba-org/quetz-frontend#121]
Hello everyone.

**A bit of context:**

I am currently working on deploying a quetz registry in my organisation, and we use keycloak as an authentication provider. Thus I am developing the support for that provider in Quetz on my side.

So far I was able to write a custom plugin using the cookiecutter mamba-org provides for that purpose. I use the quetz.authentication.oauth2.OAuthAuthenticator class to implement it, and it is still work in progress. [The repository for this plugin is already available](https://github.com/wint3ria/quetz_keycloak_auth) but I will push my work when the authentication process is functional.

**My question regarding quetz-frontend is the following:** 

Is there a way to inject the support for an additional auth provider in the frontend using a plugin architecture similar to the quetz plugins, or to configure the frontend to pick this additional provider from a config file? Should I just provide a patch to the frontend as a PR on this repository? The problem with this later option is that users who are not using the keycloak plugin would still have the support for it in the frontend. On the other hand, the necessary code to write this support is rather small and manageable.

I may have missed a functionality to implement this plugin support in the frontend, so please let me know if it's the case.

**Comment by wolfv** [comment]
Hi, I think we're writing what logins are availalbe in the "PageConfig" that is statically embedded in the generated HTML.

Then we read that in the frontend to decide whcih buttons to show: 
https://github.com/mamba-org/quetz-frontend/blob/d86a66f866be7c04c2ba50d64b5da8189e5c4cb7/quetz_frontend/backend.py#L230-L234

https://github.com/mamba-org/quetz-frontend/blob/21de4c770c0142aedb1e0981129a50e8aab2a65d/packages/login-extension/src/index.ts#L13-L26

**Comment by wint3ria** [comment]
Yes, That's what I used so far to implement the support of Keycloak. It works quite well. Should we add a feature to dynamically add custom authenticators? There are quite a few options available in the nature, Keycloak is only one of them. I'm unsure how to implement such configuration

**Comment by wint3ria** [comment]
Here:

https://github.com/wint3ria/quetz-frontend/blob/e495f8eece7c6090f3f81964c8b2a592f3a48cdf/quetz_frontend/backend.py#L231-L235

And Here:

https://github.com/wint3ria/quetz-frontend/blob/e495f8eece7c6090f3f81964c8b2a592f3a48cdf/packages/login-extension/src/index.ts#L14-L29

**Comment by wint3ria** [comment]
The Keycloak authentication plugin is functional btw :) I close this issue since my plugin is external. If anyone needs this support in the fronted, she/he may have a look at the previously mentioned patch
