### ISSUE TITLE
Stop polling the models

### ISSUE THREAD

**Issue by jtpio** [mamba-org/quetz-frontend#39]
To stop polling the models, resulting in API requests to `/jlabmock/api/kernels`, one way for now could be to access the private `_pollModels` attribute to stop the `Poll` instances.

This could be implemented by adding a new plugin that would look like the following (not tested):

```typescript
/**
 * A plugin to open documents in the main area.
 */
const stopPolling: JupyterFrontEndPlugin<void> = {
  id: 'quetz:stop-polling',
  autoStart: true,
  activate: (app: JupyterFrontEnd): void => {
  	// stop polling the sessions
    void app.serviceManager.sessions['_pollModels'].stop();

    // stop polling the terminals
    void app.serviceManager.terminals['_pollModels'].stop();
  }
};
```

**Comment by hbcarlos** [comment]
Thanks!! I'm looking into this!
