### ISSUE TITLE
Standalone Quetz theme for JupyterLab

### ISSUE THREAD

**Issue by jtpio** [mamba-org/quetz-frontend#60]
It would be interesting to check whether the styling of the quetz frontend could be extracted into its own JupyterLab extension, so that it could also be used in JupyterLab.

Then it should be possible to reuse it here after adding it as a dependency:

https://github.com/mamba-org/quetz-frontend/blob/7cde2d50eb284d2f311334ff39a428c7017314d5/src/index.ts#L20-L40

**Comment by fcollonval** [comment]
A theme project has been created: https://github.com/mamba-org/quetz-theme
Next step is to use it

**Comment by fcollonval** [comment]
Done closing.
