### ISSUE TITLE
Toggle to switch between themes

### ISSUE THREAD

**Issue by jtpio** [mamba-org/quetz-frontend#61]
It's more of a nice to have feature than something critical, but more websites have now started to expose a switch to control theme, for example on the Playwright docs:

https://playwright.dev/

https://user-images.githubusercontent.com/591645/109678589-10eb9300-7b7b-11eb-975c-838b9860c420.mp4

Maybe there could be something similar here, to toggle between to reinstalled themes.

**Comment by fcollonval** [comment]
There is now an entry in the menu if more than one theme is installed to switch between themes.
