### ISSUE TITLE
Fix react errors

### ISSUE THREAD

**Issue by jtpio** [mamba-org/quetz-frontend#64]
There are a couple of errors logged in the dev tools console after the switch to a monorepo structure in #63 :

![image](https://user-images.githubusercontent.com/591645/112644850-271d0400-8e46-11eb-90e5-7f843dcaf275.png)

This might be a dependency issue and may require regenerating the `yarn.lock` or pinning some of the underlying libraries.

**Comment by fcollonval** [comment]
Closing as resolved on main branch.
