### ISSUE TITLE
Improve federated extensions

### ISSUE THREAD

**Issue by hbcarlos** [mamba-org/quetz-frontend#69]
- [x] Install frontend in `${CONDA_ENV}/share/quetz/app'
- [x] Install extensions in `${CONDA_ENV}/share/quetz/extensions'
- [x] Create simbolic link for extensions in dev mode
- [x] Add watch extension
- [ ] Load JupyterLab extensions from `${CONDA_ENV}/share/jupyter/labextensions'

**Comment by fcollonval** [comment]
Done we should not load JupyterLab extensions as we are providing almost no equivalent plugin.
